### ISSUE TITLE
ctx.get is already used by Koa framework

### ISSUE THREAD

**Issue by nrcalowe** [junyiz/koa-http-request#1]
In the version of koa I'm using (2.5.2), ctx.get is an alias for ctx.request.get (see https://github.com/koajs/koa/blob/master/docs/api/request.md). Overwriting this causes issues with other dependencies that are using ctx.get. In my case that is the @koa/cors module. I think the get method needs to be renamed.

**Comment by junyiz** [comment]
Please use https://www.npmjs.com/package/@junyiz/request
